### PR TITLE
Support Amazon Linux 2

### LINKED ISSUE #37: Amazon Linux 2 not supported
I get the follow error on Amazon Linux 2. The package yum-cron does exist.

```
Error while evaluating a Function Call, Unsupported operatingsystemmajrelease: 2,
  module yum_cron only support 6 and 7
 (file: /etc/puppetlabs/code/environments/production/modules/yum_cron/manifests/params.pp, line: 33, column: 11)
```

Module version: 5.1.0

With module 6.0.0 I get:

```
Sep 14 12:57:15 trash-a-i puppet-agent[7802]: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Method call, Class[Yum_cron]:
Sep 14 12:57:15 trash-a-i puppet-agent[7802]:  expects a value for parameter 'package_name'
Sep 14 12:57:15 trash-a-i puppet-agent[7802]:  expects a value for parameter 'service_name'
Sep 14 12:57:15 trash-a-i puppet-agent[7802]:  expects a value for parameter 'config_path' (file: /etc/puppetlabs/code/environments/production/site.pp, line: 1, column: 37) on node trash-a-i
```

### PR DESCRIPTION
**Pull request by treydock**
Fixes #37

### CODE REVIEW

**Comment by siebrand** [comment]
Works as expected. No regressions on CentOS 7.

**Comment by treydock** [comment]
This was released with v6.1.0

**Comment by siebrand** [comment]
Very nice. Thank you!

**Comment by siebrand** [comment]
Something is wrong... I don't see settings being applied. I think that's probably because of yum_cron::config doing nothing.

**Pull request merged**
