### PR TITLE
Use validate_legacy() instead of deprecated validate_* functions

### LINKED ISSUE #11: Use validate_legacy
``validate_*`` functions has been deprecated since stdlib 4.13.0:
```
Warning: This method is deprecated, please use the stdlib validate_legacy function,
                    with Stdlib::Compat::Bool. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/yum_cron/manifests/init.pp", 34]:["/etc/puppetlabs/code/environments/production/site/profiles/manifests/base.pp", 7]
   (at /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function,
                    with Stdlib::Compat::String. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/yum_cron/manifests/init.pp", 39]:["/etc/puppetlabs/code/environments/production/site/profiles/manifests/base.pp", 7]
   (at /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function,
                    with Stdlib::Compat::Hash. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/yum_cron/manifests/init.pp", 48]:["/etc/puppetlabs/code/environments/production/site/profiles/manifests/base.pp", 7]
   (at /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function,
                    with Pattern[]. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/yum_cron/manifests/init.pp", 51]:["/etc/puppetlabs/code/environments/production/site/profiles/manifests/base.pp", 7]
   (at /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
```

``validate_legacy`` should be used instead.

### PR DESCRIPTION
**Pull request by pmuller**
Fix #11

### CODE REVIEW

**Comment by pmuller** [comment]
Hello @treydock 

Here is a PR for #11. However, I am not that experienced with tests, and I cannot make them pass.
Could you help me?

Thanks!

**Comment by treydock** [comment]
@pmuller Thanks, I am actually working on changes to drop Puppet 3 and use proper data types.  Such changes would obsolete your changes.

**Comment by treydock** [comment]
The 4.x branch contains updated changes.  May tweak things a bit to remove `Pattern` but mostly stable.

**Comment by pmuller** [comment]
Okay. That's a great news. Thank you @treydock !

**Comment by treydock** [comment]
@pmuller FYI the changes were released as 4.0.0

**Comment by pmuller** [comment]
Great. I'll migrate soon. Thanks. :)

**Comment by pmuller** [comment]
Switched to it. Works like a charm!

**Pull request closed without merging**
